- hosts: all
  become: true
  pre_tasks:
          - name: install updates
            tags: always
            apt:
                upgrade: dist
                update_cache: yes
            when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:

  - name: install apache and php packages
    tags: ubuntu,apache,apache2
    apt:
            name:
                    - apache2
                    - libapache2-mod-php
                    - tmux
                    - atop
            state: latest
    when: ansible_distribution == "Ubuntu"
- hosts: DB
  become: true
  tasks:
          - name: install maria DB Ubuntu
            tags: mariadb,db,ubuntu
            apt:
                    name:
                            - mariadb-server
                    state: latest
            when: ansible_distribution == "Ubuntu"
