- hosts: all
  become: true
  pre_tasks:

          - name: install updates
            tags: always
            apt:
                update_cache: yes
            changed_when: false
            when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
          - base
- hosts: web_server
  become: true
  roles:
          - web_server
 
- hosts: terraform
  become: true
  roles:
          - terraform

- hosts: db
  become: true
  roles:
          - db 
