  - name: install apache and php packages
    tags: ubuntu,apache,apache2
    package:

            name:
                    - "{{ apache_package_name }}"
                    - "{{ php_package_name }}"
                    - tmux
                    - atop
            state: latest
    when: ansible_distribution == "Ubuntu"

  - name: change apache conf file
    tags: conf,apache,apache2
    lineinfile:
            path: /etc/apache2/apache2.conf
            regexp: '^KeepAliveTimeout'
            line: KeepAliveTimeout 5
    when: ansible_distribution == "Ubuntu"
    notify: restart_apache

  - name: copy html file on apache www directory
    tags: ubuntu,apache,apache2
    copy:
            src: default_site.html
            dest: /var/www/html/index.html
            owner: root
            group: root
            mode: 0644
